# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Lời nhắn / Giới thiệu bản thân')),
                ('proposed_price', models.IntegerField(blank=True, null=True, verbose_name='Học phí đề xuất (VNĐ)')),
                ('status', models.CharField(choices=[('pending', 'Chờ học sinh phản hồi'), ('accepted', 'Được chấp nhận'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='class_requests.classrequest')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Danh sách Đơn ứng tuyển',
                'ordering': ['-created_at'],
                'unique_together': {('class_request', 'tutor')},
            },
        ),
    ]
