# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên môn học')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='Icon Bootstrap')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Danh sách Môn học',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, verbose_name='Giới thiệu bản thân')),
                ('experience', models.TextField(blank=True, verbose_name='Kinh nghiệm giảng dạy')),
                ('education', models.TextField(blank=True, verbose_name='Học vấn & Bằng cấp')),
                ('price_per_hour', models.IntegerField(default=150000, verbose_name='Học phí / giờ (VNĐ)')),
                ('location', models.CharField(default='Hà Nội', max_length=150, verbose_name='Khu vực dạy')),
                ('teaching_method', models.CharField(choices=[('online', 'Trực tuyến (Online)'), ('offline', 'Trực tiếp (Offline)'), ('both', 'Cả Online và Offline')], default='both', max_length=20, verbose_name='Hình thức dạy')),
                ('approval_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái phê duyệt')),
                ('admin_feedback', models.TextField(blank=True, verbose_name='Nhận xét của Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='tutors.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ Gia sư',
                'verbose_name_plural': 'Danh sách Hồ sơ Gia sư',
            },
        ),
    ]
