# Generated by Django 6.1.1 on 2026-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Danh sách Môn học'},
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('pho_thong', 'Môn phổ thông'), ('ngoai_ngu', 'Môn ngoại ngữ'), ('the_thao_nghe_thuat', 'Thể thao & Nghệ thuật')], default='pho_thong', max_length=50, verbose_name='Nhóm môn học'),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
    ]
