# Generated by Django 6.1.1 on 2026-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_subject_options_subject_category_subject_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Tệp minh chứng (Ảnh / PDF bằng cấp, chứng chỉ)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='certificate_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link minh chứng (Google Drive / OneDrive / Portfolio)'),
        ),
    ]
