# Generated by Django 6.1.1 on 2026-09-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutorprofile_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Tệp minh chứng')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tên tệp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Minh chứng Bằng cấp',
                'verbose_name_plural': 'Danh sách Minh chứng Bằng cấp',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
