# Generated by Django 6.1.1 on 2026-09-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutorcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='academic_level',
            field=models.CharField(blank=True, default='Đại học', max_length=100, verbose_name='Học vấn'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='achievements',
            field=models.TextField(blank=True, default='- Từng tham gia nhiều cuộc thi liên quan tới tiếng anh như: IOE, toán tiếng anh,...và đạt các giải cấp tỉnh, cấp quốc gia.\n- Tốt nghiệp loại Giỏi, lớp chuyên Toán - Sinh trường THPT Chuyên Quang Trung (Bình Phước).\n- Tốt nghiệp bác sĩ trường ĐH Y khoa Phạm Ngọc Thạch\n- Đã tham gia các lớp học Train Your Voice nên tự tin phát âm tiếng Anh rất chuẩn giọng Anh-Mỹ.\n- Là bác sĩ chuyên phụ trách giao tiếp với bệnh nhân người nước ngoài ở bệnh viện. - Có bằng B2 tiếng Anh.\n- Có thể giảng dạy bằng 100% Tiếng Anh với học sinh.', verbose_name='Thành tích trong học tập và dạy học'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='available_schedule',
            field=models.TextField(blank=True, default='{"tue":["chieu","toi"],"wed":["chieu","toi"],"thu":["chieu","toi"],"fri":["chieu","toi"]}', verbose_name='Lịch dạy tuần (JSON)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, default=2001, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='detailed_address',
            field=models.CharField(blank=True, default='hẻm 10 đường 30, phường Hiệp Bình, TPHCM, TP. Hồ Chí Minh', max_length=255, verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='gender',
            field=models.CharField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam')], default='Nữ', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='graduation_detail',
            field=models.CharField(blank=True, default='Tốt nghiệp Đại học - Chuyên ngành Y đa khoa - Trường Đại học Y khoa Phạm Ngọc Thạch - năm 2015', max_length=255, verbose_name='Chi tiết tốt nghiệp & Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='hometown',
            field=models.CharField(blank=True, default='Đồng Nai', max_length=150, verbose_name='Quê quán'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_topics',
            field=models.TextField(blank=True, default='Toán cấp 1, Toán cấp 2, Toán Tiếng Anh, Sinh học cấp 2, Tiếng anh cấp 1, Tiếng anh cấp 2, Tiếng anh cấp 3, Tiếng anh giao tiếp, Tiếng anh ngữ pháp, Tiếng anh cho trẻ em, Tiếng anh cho người đi làm, Chủ đề khác Tiếng Anh', verbose_name='Chủ đề dạy (phân cách bằng dấu phẩy)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='tutor_type',
            field=models.CharField(choices=[('Người đi làm', 'Người đi làm'), ('Sinh viên', 'Sinh viên'), ('Giáo viên', 'Giáo viên'), ('Cử nhân', 'Cử nhân'), ('Giảng viên', 'Giảng viên')], default='Người đi làm', max_length=50, verbose_name='Gia sư đang là'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='voice',
            field=models.CharField(blank=True, default='Miền Nam', max_length=50, verbose_name='Giọng nói'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='workplace',
            field=models.CharField(blank=True, default='Hiện đang công tác tại Bệnh viện Nhân dân Gia Định', max_length=255, verbose_name='Nơi công tác / Học tập hiện tại'),
        ),
    ]
