# Generated by Django 6.1.1 on 2026-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutorprofile_academic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='birth_date',
            field=models.CharField(blank=True, default='14/09/2001', max_length=50, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kết nối Facebook của bạn'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='identity/', verbose_name='Ảnh CMT/Căn cước/Hộ chiếu (Mặt trước)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='major',
            field=models.CharField(blank=True, default='Kinh tế quốc tế', max_length=150, verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='student_card_1',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Thẻ sinh viên/bằng/chứng chỉ 1'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='student_card_2',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Thẻ sinh viên/bằng/chứng chỉ 2'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='student_card_3',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Thẻ sinh viên/bằng/chứng chỉ 3'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='student_year',
            field=models.CharField(blank=True, default='4', max_length=50, verbose_name='Sinh viên năm'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='taught_classes_count',
            field=models.IntegerField(default=7, verbose_name='Số lượng lớp đã dạy'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(blank=True, default='Trường Đại học Ngoại thương', max_length=255, verbose_name='Trường đang học / đã tốt nghiệp'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='available_schedule',
            field=models.TextField(blank=True, default='{"mon":["sang","chieu","toi"],"tue":["sang","chieu","toi"],"wed":["sang","chieu","toi"],"thu":["sang","chieu","toi"],"fri":["sang","chieu","toi"],"sat":["sang","chieu","toi"],"sun":["sang","chieu","toi"]}', verbose_name='Lịch dạy tuần (JSON)'),
        ),
    ]
