# Generated by Django 6.1.1 on 2026-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_tutorprofile_birth_date_tutorprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='academic_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Học vấn'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='achievements',
            field=models.TextField(blank=True, default='', verbose_name='Thành tích trong học tập và dạy học'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='available_schedule',
            field=models.TextField(blank=True, default='{}', verbose_name='Lịch dạy tuần (JSON)'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='detailed_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nữ', 'Nữ'), ('Nam', 'Nam')], default='', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='graduation_detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chi tiết tốt nghiệp & Chuyên ngành'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Quê quán'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Khu vực dạy'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='major',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Chuyên ngành'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Học phí / giờ (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='student_year',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sinh viên năm'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='taught_classes_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Số lượng lớp đã dạy'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='teaching_method',
            field=models.CharField(blank=True, choices=[('online', 'Trực tuyến (Online)'), ('offline', 'Trực tiếp (Offline)'), ('both', 'Cả Online và Offline')], default='', max_length=20, verbose_name='Hình thức dạy'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='teaching_topics',
            field=models.TextField(blank=True, default='', verbose_name='Chủ đề dạy (phân cách bằng dấu phẩy)'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_type',
            field=models.CharField(blank=True, choices=[('Người đi làm', 'Người đi làm'), ('Sinh viên', 'Sinh viên'), ('Giáo viên', 'Giáo viên'), ('Cử nhân', 'Cử nhân'), ('Giảng viên', 'Giảng viên')], default='', max_length=50, verbose_name='Gia sư đang là'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Trường đang học / đã tốt nghiệp'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='voice',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Giọng nói'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nơi công tác / Học tập hiện tại'),
        ),
    ]
