# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_requests', '0001_initial'),
        ('study_requests', '0001_initial'),
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Lịch học')),
                ('hourly_rate', models.IntegerField(default=150000, verbose_name='Học phí thỏa thuận (VNĐ)')),
                ('teaching_method', models.CharField(choices=[('online', 'Trực tuyến (Online)'), ('offline', 'Trực tiếp (Offline)'), ('both', 'Linh hoạt')], default='both', max_length=20, verbose_name='Hình thức')),
                ('status', models.CharField(choices=[('in_progress', 'Đang học'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='in_progress', max_length=20, verbose_name='Trạng thái lớp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_classes', to='class_requests.classrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matched_classes', to=settings.AUTH_USER_MODEL)),
                ('study_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_classes', to='study_requests.studyrequest')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_classes', to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_matched_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lớp đã ghép',
                'verbose_name_plural': 'Danh sách Lớp đã ghép',
                'ordering': ['-created_at'],
            },
        ),
    ]
