# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài đăng')),
                ('grade', models.CharField(default='Lớp 10', max_length=50, verbose_name='Khối lớp / Trình độ')),
                ('location', models.CharField(default='Hà Nội', max_length=150, verbose_name='Khu vực học')),
                ('budget', models.IntegerField(default=200000, verbose_name='Mức thù lao dự kiến')),
                ('budget_type', models.CharField(choices=[('per_session', 'VNĐ / Buổi'), ('per_hour', 'VNĐ / Giờ'), ('per_month', 'VNĐ / Tháng')], default='per_session', max_length=20, verbose_name='Đơn vị ngân sách')),
                ('schedule', models.CharField(max_length=200, verbose_name='Lịch học dự kiến')),
                ('teaching_method', models.CharField(choices=[('online', 'Trực tuyến (Online)'), ('offline', 'Trực tiếp (Offline)'), ('both', 'Linh hoạt Online/Offline')], default='both', max_length=20, verbose_name='Hình thức học')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Đang tìm gia sư'), ('accepted', 'Đã ghép lớp'), ('closed', 'Đã đóng bài'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_requests', to='tutors.subject')),
            ],
            options={
                'verbose_name': 'Yêu cầu tìm gia sư',
                'verbose_name_plural': 'Danh sách yêu cầu tìm gia sư',
                'ordering': ['-created_at'],
            },
        ),
    ]
