# Generated by Django 6.1.1 on 2026-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_requests', '0002_classrequest_sessions_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrequest',
            name='schedule',
            field=models.CharField(max_length=200, verbose_name='Thời gian có thể học'),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='sessions_per_week',
            field=models.CharField(blank=True, default='2-3 buổi/tuần', max_length=50, verbose_name='Số buổi / tuần'),
        ),
    ]
