# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matched_classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 sao - Kém'), (2, '2 sao - Trung bình'), (3, '3 sao - Khá'), (4, '4 sao - Tốt'), (5, '5 sao - Xuất sắc')], default=5, verbose_name='Đánh giá sao')),
                ('comment', models.TextField(verbose_name='Nhận xét về gia sư')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='matched_classes.matchedclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá gia sư',
                'verbose_name_plural': 'Danh sách Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
