# Generated by Django 6.1.1 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='Lớp 10', max_length=50, verbose_name='Khối lớp / Trình độ')),
                ('schedule', models.CharField(max_length=200, verbose_name='Lịch học mong muốn')),
                ('teaching_method', models.CharField(choices=[('online', 'Trực tuyến (Online)'), ('offline', 'Trực tiếp (Offline)'), ('both', 'Linh hoạt')], default='both', max_length=20, verbose_name='Hình thức học')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú / Mục tiêu học tập')),
                ('status', models.CharField(choices=[('pending', 'Chờ gia sư phản hồi'), ('accepted', 'Đã đồng ý'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_study_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_requests', to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_study_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu học trực tiếp',
                'verbose_name_plural': 'Danh sách Yêu cầu học trực tiếp',
                'ordering': ['-created_at'],
            },
        ),
    ]
