# Generated by Django 6.1.1 on 2026-09-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ / Khu vực học'),
        ),
    ]
