# Generated by Django 6.1.1 on 2026-09-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_requests', '0002_studyrequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='sessions_per_week',
            field=models.CharField(blank=True, default='3 buổi/tuần', max_length=50, verbose_name='Số buổi / tuần'),
        ),
    ]
